title: Реконструкция перевода «Слова о полку Игореве»
description: Экспериментальный проект по восстановлению идеального современного перевода «Слова о полку Игореве»
show_downloads: false
google_analytics:
theme: jekyll-theme-time-machine
